version: '3'

volumes:
  life_writer_mariadb:

services:
  life_writer:
    build: LifeWriter/
    container_name: life_writer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    links:
      - life_writer_db

  life_writer_db:
    image: mariadb
    container_name: life_writer_db
    restart: always
    volumes:
      - life_writer_mariadb:/var/lib/mysql
    ports:
      - 6080:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: life_writer
      MYSQL_USER: egor
      MYSQL_PASSWORD: 123123
